# Generated by Django 5.0.6 on 2024-06-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, default="", max_length=2083, null=True),
        ),
    ]
